void printCards(Node *head);
void printPicture(char str[]);
void deckSize(int place);
void displayCards(Node*playerHead, Node*opTail, Node*tableHead, int turn);
void buffer(char *text);
void playerBuffer();
void dealText();
void endText();
int quitText();
void helpText();
void invalidCaptureText();
void printMenu();
